version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  go: circleci/go@1.6.0

jobs:
  install-dependencies:
    docker:
      - image: cimg/go:1.16.4
    steps:
      - checkout
      - go/mod-download
      - persist_to_workspace:
          root: ~/
          paths:
            - go
            - project
  run-linter:
    docker:
      - image: cimg/go:1.16.4
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: install golangci-lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
      - run:
          name: run linter
          command: |
            golangci-lint run ./...
  unit-tests:
    docker:
      - image: cimg/go:1.16.4
    steps:
      - attach_workspace:
          at: ~/
      - go/test:
          covermode: atomic
          failfast: true
          race: true
  push-to-ecr:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - aws-ecr/build-and-push-image:
          attach-workspace: true
          checkout: false
          repo: $ECR_REPO
          tag: $CIRCLE_TAG
          workspace-root: ~/
          extra-build-args: -t twitter-lambda
workflows:
  build:
    jobs:
      - install-dependencies:
          filters:
            tags:
              only: /^v.*/
      - run-linter:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /^v.*/
      - unit-tests:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /^v.*/
      - push-to-ecr:
          context: AWS
          requires:
            - unit-tests
            - run-linter
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
